#!/usr/bin/env python3
"""Regenerate vllm-archive-manifest.yaml from the table below (run from repo root optional)."""
from __future__ import annotations

import pathlib

import yaml

ENTRIES: list[dict] = [
    {
        "hf_repo": "deepseek-ai/deepseek-coder-6.7b-instruct",
        "approx_disk_gib": 13.0,
        "gated": False,
        "covers_ollama_tags": ["deepseek-coder:6.7b"],
        "notes": "vLLM: causal LM code model.",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-Coder-7B-Instruct",
        "approx_disk_gib": 14.0,
        "gated": False,
        "covers_ollama_tags": ["qwen2.5-coder:7b"],
        "notes": "",
    },
    {
        "hf_repo": "meta-llama/Meta-Llama-3.1-8B-Instruct",
        "approx_disk_gib": 15.0,
        "gated": True,
        "covers_ollama_tags": ["llama3.1:8b-instruct-q4_K_M"],
        "notes": "Accept Meta license on HF; HF_TOKEN required.",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
        "approx_disk_gib": 15.0,
        "gated": False,
        "covers_ollama_tags": [
            "deepseek-r1:8b-0528-qwen3-q4_K_M",
            "deepseek-r1:8b-llama-distill-q4_K_M",
        ],
        "notes": "Ollama 'qwen3' tag name; HF publishes Llama-8B R1 distill. If you need Qwen-7B instead, use DeepSeek-R1-Distill-Qwen-7B (extra row).",
    },
    {
        "hf_repo": "google/gemma-4-E2B-it",
        "approx_disk_gib": 29.0,
        "gated": True,
        "covers_ollama_tags": ["gemma4:e2b-it-q4_K_M", "gemma4:e2b-it-q8_0"],
        "notes": "Gemma license on HF; ~30 GiB full weights per HF snapshot.",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
        "approx_disk_gib": 30.0,
        "gated": False,
        "covers_ollama_tags": ["deepseek-coder-v2:16b"],
        "notes": "MoE lite instruct; aligns with Ollama 16B coder line.",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
        "approx_disk_gib": 28.0,
        "gated": False,
        "covers_ollama_tags": ["deepseek-r1:14b-qwen-distill-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-Coder-14B-Instruct",
        "approx_disk_gib": 28.0,
        "gated": False,
        "covers_ollama_tags": ["qwen2.5-coder:14b-instruct-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "bigcode/starcoder2-15b",
        "approx_disk_gib": 28.0,
        "gated": False,
        "covers_ollama_tags": ["starcoder2:15b"],
        "notes": "Base code model; add starcoder2-15b-instruct separately if you need instruct.",
    },
    {
        "hf_repo": "google/gemma-4-E4B-it",
        "approx_disk_gib": 18.0,
        "gated": True,
        "covers_ollama_tags": ["gemma4:e4b-it-q4_K_M", "gemma4:e4b-it-q8_0"],
        "notes": "Gemma license.",
    },
    {
        "hf_repo": "google/gemma-4-26B-A4B-it",
        "approx_disk_gib": 56.0,
        "gated": True,
        "covers_ollama_tags": ["gemma4:26b-a4b-it-q4_K_M", "gemma4:26b-a4b-it-q8_0"],
        "notes": "MoE; disk is total shard size order-of-magnitude.",
    },
    {
        "hf_repo": "google/gemma-4-31B-it",
        "approx_disk_gib": 165.0,
        "gated": True,
        "covers_ollama_tags": ["gemma4:31b-it-q4_K_M", "gemma4:31b-it-q8_0"],
        "notes": "Very large; confirm D5 free space or use D2 root.",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-Coder-32B-Instruct",
        "approx_disk_gib": 62.0,
        "gated": False,
        "covers_ollama_tags": ["qwen2.5-coder:32b-instruct-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "deepseek-ai/deepseek-coder-33b-instruct",
        "approx_disk_gib": 62.0,
        "gated": False,
        "covers_ollama_tags": ["deepseek-coder:33b-instruct-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "mistralai/Mixtral-8x7B-Instruct-v0.1",
        "approx_disk_gib": 87.0,
        "gated": False,
        "covers_ollama_tags": ["mixtral:8x7b-instruct-v0.1-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "dphn/dolphin-2.6-mistral-7b",
        "approx_disk_gib": 14.0,
        "gated": False,
        "covers_ollama_tags": ["dolphin-mistral:latest"],
        "notes": "HF canonical id resolves from cognitivecomputations mirror.",
    },
    {
        "hf_repo": "cognitivecomputations/Dolphin3.0-Llama3.1-8B",
        "approx_disk_gib": 16.0,
        "gated": False,
        "covers_ollama_tags": ["dolphin-llama3:8b"],
        "notes": "",
    },
    {
        "hf_repo": "huihui-ai/Dolphin3.0-Llama3.1-8B-abliterated",
        "approx_disk_gib": 16.0,
        "gated": False,
        "covers_ollama_tags": ["huihui_ai/dolphin3-abliterated:latest"],
        "notes": "",
    },
    {
        "hf_repo": "dphn/dolphin-2.7-mixtral-8x7b",
        "approx_disk_gib": 87.0,
        "gated": False,
        "covers_ollama_tags": ["dolphin-mixtral:8x7b", "dolphin-mixtral:8x7b-v2.7"],
        "notes": "Single HF snapshot covers both Ollama tags; newer v2.7 may differ—revisit if you need exact parity.",
    },
    {
        "hf_repo": "cognitivecomputations/dolphin-2.9.2-qwen2-72b",
        "approx_disk_gib": 145.0,
        "gated": False,
        "covers_ollama_tags": ["dolphin-llama3:70b-v2.9-q4_K_M"],
        "notes": "Ollama 70B dolphin line → HF 72B Qwen dolphin weights.",
    },
    {
        "hf_repo": "mlabonne/NeuralDaredevil-8B-abliterated",
        "approx_disk_gib": 16.0,
        "gated": False,
        "covers_ollama_tags": [
            "rolandroland/llama3.1-uncensored:latest",
            "closex/neuraldaredevil-8b-abliterated:latest",
        ],
        "notes": "Stand-in for rolandroland Ollama tag (same class of weights as NeuralDaredevil).",
    },
    {
        "hf_repo": "meta-llama/Llama-3.3-70B-Instruct",
        "approx_disk_gib": 132.0,
        "gated": True,
        "covers_ollama_tags": ["llama3.3:70b-instruct-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "meta-llama/Meta-Llama-3.1-70B-Instruct",
        "approx_disk_gib": 132.0,
        "gated": True,
        "covers_ollama_tags": ["llama3.1:70b-instruct-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-72B-Instruct",
        "approx_disk_gib": 135.0,
        "gated": False,
        "covers_ollama_tags": ["qwen2.5:72b-instruct-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "huihui-ai/Llama-3.3-70B-Instruct-abliterated",
        "approx_disk_gib": 132.0,
        "gated": False,
        "covers_ollama_tags": ["huihui_ai/llama3.3-abliterated:70b"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3-8B",
        "approx_disk_gib": 16.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3:8b-q4_K_M"],
        "notes": "Full BF16/chat weights; not GGUF.",
    },
    {
        "hf_repo": "Qwen/Qwen3-14B",
        "approx_disk_gib": 28.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3:14b-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3-30B-A3B-Instruct-2507",
        "approx_disk_gib": 65.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3:30b-a3b-instruct-2507-q4_K_M"],
        "notes": "MoE instruct line.",
    },
    {
        "hf_repo": "Qwen/Qwen3-32B",
        "approx_disk_gib": 62.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3:32b-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "meta-llama/Llama-3.2-3B-Instruct",
        "approx_disk_gib": 6.0,
        "gated": True,
        "covers_ollama_tags": ["llama3.2:3b"],
        "notes": "",
    },
    {
        "hf_repo": "BAAI/bge-m3",
        "approx_disk_gib": 2.0,
        "gated": False,
        "covers_ollama_tags": ["bge-m3"],
        "notes": "Embedding / RAG.",
    },
    {
        "hf_repo": "ibm-granite/granite-embedding-107m-multilingual",
        "approx_disk_gib": 0.5,
        "gated": False,
        "covers_ollama_tags": ["granite-embedding"],
        "notes": "",
    },
    {
        "hf_repo": "nomic-ai/nomic-embed-text-v1.5",
        "approx_disk_gib": 0.5,
        "gated": False,
        "covers_ollama_tags": ["nomic-embed-text"],
        "notes": "v1.5 supersedes v1 for new work.",
    },
    {
        "hf_repo": "google/embeddinggemma-300m",
        "approx_disk_gib": 0.6,
        "gated": True,
        "covers_ollama_tags": ["embeddinggemma"],
        "notes": "Gemma-family license.",
    },
    {
        "hf_repo": "Snowflake/snowflake-arctic-embed-m-long",
        "approx_disk_gib": 1.0,
        "gated": False,
        "covers_ollama_tags": ["snowflake-arctic-embed"],
        "notes": "Closest HF match to Ollama snowflake-arctic-embed line.",
    },
    {
        "hf_repo": "mixedbread-ai/mxbai-embed-large-v1",
        "approx_disk_gib": 0.7,
        "gated": False,
        "covers_ollama_tags": ["mxbai-embed-large"],
        "notes": "",
    },
    {
        "hf_repo": "BAAI/bge-large-en-v1.5",
        "approx_disk_gib": 1.3,
        "gated": False,
        "covers_ollama_tags": ["bge-large"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3-Embedding-4B",
        "approx_disk_gib": 9.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3-embedding"],
        "notes": "Matches ~4–5 GiB Ollama class better than 0.6B/8B extremes.",
    },
    {
        "hf_repo": "Qwen/Qwen3.5-4B-Instruct-2507",
        "approx_disk_gib": 8.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3.5:4b-q4_K_M", "qwen3.5:4b-bf16"],
        "notes": "One snapshot for both Ollama quants.",
    },
    {
        "hf_repo": "google/gemma-3-4b-it",
        "approx_disk_gib": 8.0,
        "gated": True,
        "covers_ollama_tags": ["gemma3:4b-it-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "google/medgemma-4b-it",
        "approx_disk_gib": 8.0,
        "gated": True,
        "covers_ollama_tags": ["alibayram/medgemma:4b"],
        "notes": "MedGemma ToU on HF.",
    },
    {
        "hf_repo": "mistralai/Mathstral-7B-v0.1",
        "approx_disk_gib": 15.0,
        "gated": False,
        "covers_ollama_tags": ["mathstral:7b"],
        "notes": "",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
        "approx_disk_gib": 14.0,
        "gated": False,
        "covers_ollama_tags": ["deepseek-r1:7b-qwen-distill-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-VL-7B-Instruct",
        "approx_disk_gib": 16.0,
        "gated": False,
        "covers_ollama_tags": ["qwen2.5vl:7b"],
        "notes": "Vision-language.",
    },
    {
        "hf_repo": "Qwen/Qwen3.5-9B",
        "approx_disk_gib": 18.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3.5:9b-q4_K_M", "qwen3.5:9b-bf16"],
        "notes": "Single base/instruct snapshot for both Ollama tags.",
    },
    {
        "hf_repo": "microsoft/Phi-4",
        "approx_disk_gib": 28.0,
        "gated": False,
        "covers_ollama_tags": ["phi4:14b-q4_K_M"],
        "notes": "Official Phi-4 (14B class) for vLLM.",
    },
    {
        "hf_repo": "mistralai/Mistral-Small-24B-Instruct-2501",
        "approx_disk_gib": 48.0,
        "gated": False,
        "covers_ollama_tags": ["mistral-small3.2:24b-instruct-2506-q4_K_M"],
        "notes": "Ollama tag is 2506 line; HF 2501 instruct is the supported vLLM baseline—swap if Mistral publishes 2506 weights.",
    },
    {
        "hf_repo": "google/gemma-3-27b-it",
        "approx_disk_gib": 54.0,
        "gated": True,
        "covers_ollama_tags": ["gemma3:27b-it-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3.5-27B",
        "approx_disk_gib": 54.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3.5:27b-q4_K_M", "qwen3.5:27b-bf16"],
        "notes": "",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
        "approx_disk_gib": 62.0,
        "gated": False,
        "covers_ollama_tags": ["deepseek-r1:32b-qwen-distill-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/QwQ-32B",
        "approx_disk_gib": 62.0,
        "gated": False,
        "covers_ollama_tags": ["qwq:32b-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-VL-32B-Instruct",
        "approx_disk_gib": 65.0,
        "gated": False,
        "covers_ollama_tags": ["qwen2.5vl:32b-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3.5-35B-A3B",
        "approx_disk_gib": 72.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3.5:35b-a3b-q4_K_M"],
        "notes": "MoE.",
    },
    {
        "hf_repo": "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
        "approx_disk_gib": 132.0,
        "gated": True,
        "covers_ollama_tags": ["nemotron:70b-instruct-q4_K_M"],
        "notes": "NVIDIA license gating on HF.",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
        "approx_disk_gib": 132.0,
        "gated": False,
        "covers_ollama_tags": ["deepseek-r1:70b-llama-distill-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-VL-72B-Instruct",
        "approx_disk_gib": 135.0,
        "gated": False,
        "covers_ollama_tags": ["qwen2.5vl:72b-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3.5-122B-A10B",
        "approx_disk_gib": 228.0,
        "gated": False,
        "covers_ollama_tags": ["qwen3.5:122b-a10b-q4_K_M"],
        "notes": "Largest MoE in queue; ensure destination filesystem has headroom.",
    },
]


def main() -> None:
    root = pathlib.Path(__file__).resolve().parents[1]
    out = root / "config" / "vllm-archive-manifest.yaml"
    total = round(sum(e["approx_disk_gib"] for e in ENTRIES), 1)
    doc = {
        "schema_version": 1,
        "description": "Hugging Face repos for vLLM-oriented archival (BF16/safetensors), deduped from ollama-hosting/registry/TARGET_QUEUE_ORDERED.txt.",
        "updated_note": "Regenerate via scripts/_generate_vllm_manifest.py",
        "default_archive_root": "/mnt/models/d5/vllm",
        "bandwidth_mib_per_s_default": 2,
        "approx_total_disk_gib_sum": total,
        "approx_total_disk_gib_disclaimer": "Rough order-of-magnitude from HF shard sizes / param counts; actual hub cache size can differ. Sum is ~2.7+ TiB — exceeds a ~916 GiB D5; use D2 or split.",
        "entries": ENTRIES,
    }
    out.write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"Wrote {out} ({len(ENTRIES)} repos, ~{total} GiB summed)")


if __name__ == "__main__":
    main()
