#!/usr/bin/env python3
"""Regenerate vllm-archive-manifest.yaml from the table below (run from repo root optional)."""
from __future__ import annotations

import pathlib

import yaml

# No entry should exceed this (binary GiB, approximate HF full-weight size).
MAX_APPROX_DISK_GIB = 120.0

# Hugging Face repos dropped from the former Ollama-queue mapping because they exceed MAX_APPROX_DISK_GIB.
EXCLUDED_OVER_LIMIT: list[dict] = [
    {
        "hf_repo": "google/gemma-4-31B-it",
        "approx_disk_gib": 165.0,
        "former_covers_ollama_tags": ["gemma4:31b-it-q4_K_M", "gemma4:31b-it-q8_0"],
    },
    {
        "hf_repo": "cognitivecomputations/dolphin-2.9.2-qwen2-72b",
        "approx_disk_gib": 145.0,
        "former_covers_ollama_tags": ["dolphin-llama3:70b-v2.9-q4_K_M"],
    },
    {
        "hf_repo": "meta-llama/Llama-3.3-70B-Instruct",
        "approx_disk_gib": 132.0,
        "former_covers_ollama_tags": ["llama3.3:70b-instruct-q4_K_M"],
    },
    {
        "hf_repo": "meta-llama/Meta-Llama-3.1-70B-Instruct",
        "approx_disk_gib": 132.0,
        "former_covers_ollama_tags": ["llama3.1:70b-instruct-q4_K_M"],
    },
    {
        "hf_repo": "Qwen/Qwen2.5-72B-Instruct",
        "approx_disk_gib": 135.0,
        "former_covers_ollama_tags": ["qwen2.5:72b-instruct-q4_K_M"],
    },
    {
        "hf_repo": "huihui-ai/Llama-3.3-70B-Instruct-abliterated",
        "approx_disk_gib": 132.0,
        "former_covers_ollama_tags": ["huihui_ai/llama3.3-abliterated:70b"],
    },
    {
        "hf_repo": "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
        "approx_disk_gib": 132.0,
        "former_covers_ollama_tags": ["nemotron:70b-instruct-q4_K_M"],
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
        "approx_disk_gib": 132.0,
        "former_covers_ollama_tags": ["deepseek-r1:70b-llama-distill-q4_K_M"],
    },
    {
        "hf_repo": "Qwen/Qwen2.5-VL-72B-Instruct",
        "approx_disk_gib": 135.0,
        "former_covers_ollama_tags": ["qwen2.5vl:72b-q4_K_M"],
    },
    {
        "hf_repo": "Qwen/Qwen3.5-122B-A10B",
        "approx_disk_gib": 228.0,
        "former_covers_ollama_tags": ["qwen3.5:122b-a10b-q4_K_M"],
    },
]

# target_category:
#   core_queue — deduped from ollama-hosting/registry/TARGET_QUEUE_ORDERED.txt (after >120 GiB removals)
#   specialist — embeddings / code / math / VLM / reasoning from registry-specialists + investigation
#   uncensored — abliterated / merge uncensored lines (hostable under cap)
ENTRIES: list[dict] = [
    # --- core_queue (former TARGET_QUEUE_ORDERED mapping, <= 120 GiB) ---
    {
        "hf_repo": "deepseek-ai/deepseek-coder-6.7b-instruct",
        "approx_disk_gib": 13.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["deepseek-coder:6.7b"],
        "notes": "vLLM: causal LM code model.",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-Coder-7B-Instruct",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen2.5-coder:7b"],
        "notes": "",
    },
    {
        "hf_repo": "meta-llama/Meta-Llama-3.1-8B-Instruct",
        "approx_disk_gib": 15.0,
        "gated": True,
        "target_category": "core_queue",
        "covers_ollama_tags": ["llama3.1:8b-instruct-q4_K_M"],
        "notes": "Accept Meta license on HF; HF_TOKEN required.",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
        "approx_disk_gib": 15.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["deepseek-r1:8b-llama-distill-q4_K_M"],
        "notes": "Llama-8B R1 distill. For Qwen3-8B 0528 lineage see specialist DeepSeek-R1-0528-Qwen3-8B.",
    },
    {
        "hf_repo": "google/gemma-4-E2B-it",
        "approx_disk_gib": 29.0,
        "gated": True,
        "target_category": "core_queue",
        "covers_ollama_tags": ["gemma4:e2b-it-q4_K_M", "gemma4:e2b-it-q8_0"],
        "notes": "Gemma license on HF; ~30 GiB full weights per HF snapshot.",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
        "approx_disk_gib": 30.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["deepseek-coder-v2:16b"],
        "notes": "MoE lite instruct; aligns with Ollama 16B coder line.",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
        "approx_disk_gib": 28.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["deepseek-r1:14b-qwen-distill-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-Coder-14B-Instruct",
        "approx_disk_gib": 28.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen2.5-coder:14b-instruct-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "bigcode/starcoder2-15b",
        "approx_disk_gib": 28.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["starcoder2:15b"],
        "notes": "Base code model; see specialist TechxGenus/starcoder2-15b-instruct for instruct.",
    },
    {
        "hf_repo": "google/gemma-4-E4B-it",
        "approx_disk_gib": 18.0,
        "gated": True,
        "target_category": "core_queue",
        "covers_ollama_tags": ["gemma4:e4b-it-q4_K_M", "gemma4:e4b-it-q8_0"],
        "notes": "Gemma license.",
    },
    {
        "hf_repo": "google/gemma-4-26B-A4B-it",
        "approx_disk_gib": 56.0,
        "gated": True,
        "target_category": "core_queue",
        "covers_ollama_tags": ["gemma4:26b-a4b-it-q4_K_M", "gemma4:26b-a4b-it-q8_0"],
        "notes": "MoE; disk is total shard size order-of-magnitude.",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-Coder-32B-Instruct",
        "approx_disk_gib": 62.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen2.5-coder:32b-instruct-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "deepseek-ai/deepseek-coder-33b-instruct",
        "approx_disk_gib": 62.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["deepseek-coder:33b-instruct-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "mistralai/Mixtral-8x7B-Instruct-v0.1",
        "approx_disk_gib": 87.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["mixtral:8x7b-instruct-v0.1-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "dphn/dolphin-2.6-mistral-7b",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["dolphin-mistral:latest"],
        "notes": "HF canonical id resolves from cognitivecomputations mirror.",
    },
    {
        "hf_repo": "cognitivecomputations/Dolphin3.0-Llama3.1-8B",
        "approx_disk_gib": 16.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["dolphin-llama3:8b"],
        "notes": "",
    },
    {
        "hf_repo": "huihui-ai/Dolphin3.0-Llama3.1-8B-abliterated",
        "approx_disk_gib": 16.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["huihui_ai/dolphin3-abliterated:latest"],
        "notes": "",
    },
    {
        "hf_repo": "dphn/dolphin-2.7-mixtral-8x7b",
        "approx_disk_gib": 87.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["dolphin-mixtral:8x7b", "dolphin-mixtral:8x7b-v2.7"],
        "notes": "Single HF snapshot covers both Ollama tags; newer v2.7 may differ—revisit if you need exact parity.",
    },
    {
        "hf_repo": "mlabonne/NeuralDaredevil-8B-abliterated",
        "approx_disk_gib": 16.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": [
            "rolandroland/llama3.1-uncensored:latest",
            "closex/neuraldaredevil-8b-abliterated:latest",
        ],
        "notes": "Stand-in for rolandroland Ollama tag (same class of weights as NeuralDaredevil).",
    },
    {
        "hf_repo": "Qwen/Qwen3-8B",
        "approx_disk_gib": 16.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen3:8b-q4_K_M"],
        "notes": "Full BF16/chat weights; not GGUF.",
    },
    {
        "hf_repo": "Qwen/Qwen3-14B",
        "approx_disk_gib": 28.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen3:14b-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3-30B-A3B-Instruct-2507",
        "approx_disk_gib": 65.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen3:30b-a3b-instruct-2507-q4_K_M"],
        "notes": "MoE instruct line.",
    },
    {
        "hf_repo": "Qwen/Qwen3-32B",
        "approx_disk_gib": 62.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen3:32b-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "meta-llama/Llama-3.2-3B-Instruct",
        "approx_disk_gib": 6.0,
        "gated": True,
        "target_category": "core_queue",
        "covers_ollama_tags": ["llama3.2:3b"],
        "notes": "",
    },
    {
        "hf_repo": "BAAI/bge-m3",
        "approx_disk_gib": 2.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["bge-m3"],
        "notes": "Embedding / RAG.",
    },
    {
        "hf_repo": "ibm-granite/granite-embedding-107m-multilingual",
        "approx_disk_gib": 0.5,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["granite-embedding"],
        "notes": "",
    },
    {
        "hf_repo": "nomic-ai/nomic-embed-text-v1.5",
        "approx_disk_gib": 0.5,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["nomic-embed-text"],
        "notes": "v1.5 supersedes v1 for new work.",
    },
    {
        "hf_repo": "google/embeddinggemma-300m",
        "approx_disk_gib": 0.6,
        "gated": True,
        "target_category": "core_queue",
        "covers_ollama_tags": ["embeddinggemma"],
        "notes": "Gemma-family license.",
    },
    {
        "hf_repo": "Snowflake/snowflake-arctic-embed-m-long",
        "approx_disk_gib": 1.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["snowflake-arctic-embed"],
        "notes": "Closest HF match to Ollama snowflake-arctic-embed line.",
    },
    {
        "hf_repo": "mixedbread-ai/mxbai-embed-large-v1",
        "approx_disk_gib": 0.7,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["mxbai-embed-large"],
        "notes": "",
    },
    {
        "hf_repo": "BAAI/bge-large-en-v1.5",
        "approx_disk_gib": 1.3,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["bge-large"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3-Embedding-4B",
        "approx_disk_gib": 9.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen3-embedding"],
        "notes": "Matches ~4–5 GiB Ollama class better than 0.6B/8B extremes.",
    },
    {
        "hf_repo": "Qwen/Qwen3-4B-Instruct-2507",
        "approx_disk_gib": 8.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen3.5:4b-q4_K_M", "qwen3.5:4b-bf16"],
        "notes": "HF id is Qwen3 (not Qwen3.5); Ollama tags use qwen3.5:4b-* for this snapshot.",
    },
    {
        "hf_repo": "google/gemma-3-4b-it",
        "approx_disk_gib": 8.0,
        "gated": True,
        "target_category": "core_queue",
        "covers_ollama_tags": ["gemma3:4b-it-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "google/medgemma-4b-it",
        "approx_disk_gib": 8.0,
        "gated": True,
        "target_category": "core_queue",
        "covers_ollama_tags": ["alibayram/medgemma:4b"],
        "notes": "MedGemma ToU on HF.",
    },
    {
        "hf_repo": "mistralai/Mathstral-7B-v0.1",
        "approx_disk_gib": 15.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["mathstral:7b"],
        "notes": "",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["deepseek-r1:7b-qwen-distill-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-VL-7B-Instruct",
        "approx_disk_gib": 16.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen2.5vl:7b"],
        "notes": "Vision-language.",
    },
    {
        "hf_repo": "Qwen/Qwen3.5-9B",
        "approx_disk_gib": 18.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen3.5:9b-q4_K_M", "qwen3.5:9b-bf16"],
        "notes": "Single base/instruct snapshot for both Ollama tags.",
    },
    {
        "hf_repo": "microsoft/Phi-4",
        "approx_disk_gib": 28.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["phi4:14b-q4_K_M"],
        "notes": "Official Phi-4 (14B class) for vLLM.",
    },
    {
        "hf_repo": "mistralai/Mistral-Small-24B-Instruct-2501",
        "approx_disk_gib": 48.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["mistral-small3.2:24b-instruct-2506-q4_K_M"],
        "notes": "Ollama tag is 2506 line; HF 2501 instruct is the supported vLLM baseline—swap if Mistral publishes 2506 weights.",
    },
    {
        "hf_repo": "google/gemma-3-27b-it",
        "approx_disk_gib": 54.0,
        "gated": True,
        "target_category": "core_queue",
        "covers_ollama_tags": ["gemma3:27b-it-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3.5-27B",
        "approx_disk_gib": 54.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen3.5:27b-q4_K_M", "qwen3.5:27b-bf16"],
        "notes": "",
    },
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
        "approx_disk_gib": 62.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["deepseek-r1:32b-qwen-distill-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/QwQ-32B",
        "approx_disk_gib": 62.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwq:32b-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-VL-32B-Instruct",
        "approx_disk_gib": 65.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen2.5vl:32b-q4_K_M"],
        "notes": "",
    },
    {
        "hf_repo": "Qwen/Qwen3.5-35B-A3B",
        "approx_disk_gib": 72.0,
        "gated": False,
        "target_category": "core_queue",
        "covers_ollama_tags": ["qwen3.5:35b-a3b-q4_K_M"],
        "notes": "MoE.",
    },
    # --- specialist (registry-specialists + hostable picks, all <= 120 GiB) ---
    {
        "hf_repo": "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B",
        "approx_disk_gib": 16.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": ["deepseek-r1:8b-0528-qwen3-q4_K_M"],
        "notes": "Official Qwen3-8B R1 0528 distill; complements DeepSeek-R1-Distill-Llama-8B.",
    },
    {
        "hf_repo": "TechxGenus/starcoder2-15b-instruct",
        "approx_disk_gib": 28.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Code instruct finetune; bigcode/starcoder2-15b-instruct is often gated—community weights for vLLM.",
    },
    {
        "hf_repo": "open-r1/OlympicCoder-7B",
        "approx_disk_gib": 15.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Open R1 code/reasoning line; from registry-specialists.",
    },
    {
        "hf_repo": "open-r1/OlympicCoder-32B",
        "approx_disk_gib": 62.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Open R1 code/reasoning at 32B; registry open-r1/OlympicCoder-32B.",
    },
    {
        "hf_repo": "Qwen/Qwen2.5-Math-7B-Instruct",
        "approx_disk_gib": 15.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Math specialist; complements Mathstral.",
    },
    {
        "hf_repo": "deepseek-ai/deepseek-math-7b-instruct",
        "approx_disk_gib": 15.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "DeepSeek math instruct; registry discipline:math.",
    },
    {
        "hf_repo": "Alibaba-NLP/gte-Qwen2-7B-instruct",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "MTEB-class embedding; TARGET_MODEL_LIST residual / specialists.",
    },
    {
        "hf_repo": "intfloat/e5-mistral-7b-instruct",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "English instruct embedding for RAG.",
    },
    {
        "hf_repo": "BAAI/bge-en-icl",
        "approx_disk_gib": 1.5,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "English ICL retrieval embedding; registry-specialists.",
    },
    {
        "hf_repo": "meta-llama/Llama-3.2-11B-Vision-Instruct",
        "approx_disk_gib": 22.0,
        "gated": True,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Meta open VLM; gated. Specialist doc / registry.",
    },
    # --- discipline specialists: math / legal encoders / chemistry encoders+MolT5 ---
    {
        "hf_repo": "Qwen/Qwen2.5-Math-1.5B-Instruct",
        "approx_disk_gib": 3.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Tiny math instruct; registry-specialists.",
    },
    {
        "hf_repo": "Qwen/Qwen2-Math-7B-Instruct",
        "approx_disk_gib": 15.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Qwen2 math instruct line.",
    },
    {
        "hf_repo": "AI-MO/NuminaMath-7B-TIR",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Tool-integrated math / olympiad.",
    },
    {
        "hf_repo": "AI-MO/NuminaMath-7B-CoT",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "CoT math specialist; pairs with NuminaMath-7B-TIR.",
    },
    {
        "hf_repo": "qingy2019/Qwen2.5-Math-14B-Instruct",
        "approx_disk_gib": 28.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Community 14B math instruct (Apache-2.0 on HF).",
    },
    {
        "hf_repo": "meta-math/MetaMath-Mistral-7B",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "MetaMath on Mistral-7B.",
    },
    {
        "hf_repo": "WizardLMTeam/WizardMath-7B-V1.1",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "WizardMath 7B; confirm license on HF card before commercial use.",
    },
    {
        "hf_repo": "nlpaueb/legal-bert-base-uncased",
        "approx_disk_gib": 0.5,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Legal-domain BERT encoder (transformers; not causal vLLM).",
    },
    {
        "hf_repo": "nlpaueb/legal-bert-small-uncased",
        "approx_disk_gib": 0.2,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Small Legal-BERT encoder.",
    },
    {
        "hf_repo": "pile-of-law/legalbert-large-1.7M-2",
        "approx_disk_gib": 1.3,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Pile-of-Law LegalBERT-large; CC BY-NC-SA dataset — check NC terms.",
    },
    {
        "hf_repo": "language-plus-molecules/molt5-base-smiles2caption-LPM24",
        "approx_disk_gib": 0.5,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "MolT5 SMILES↔caption seq2seq.",
    },
    {
        "hf_repo": "DeepChem/ChemBERTa-77M-MLM",
        "approx_disk_gib": 0.3,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "ChemBERTa 77M MLM encoder.",
    },
    {
        "hf_repo": "Derify/ModChemBERT-MLM-DAPT-TAFT",
        "approx_disk_gib": 0.2,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "ModernBERT-style chemistry SMILES encoder.",
    },
    # --- science + management / finance specialists ---
    {
        "hf_repo": "allenai/OLMo-2-1124-7B-Instruct",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "OLMo 7B instruct; open science / NLP reproducibility.",
    },
    {
        "hf_repo": "allenai/scibert_scivocab_uncased",
        "approx_disk_gib": 0.4,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "SciBERT encoder (transformers).",
    },
    {
        "hf_repo": "m3rg-iitd/matscibert",
        "approx_disk_gib": 0.4,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "MatSciBERT materials-science encoder.",
    },
    {
        "hf_repo": "nvidia/OpenMath-Nemotron-1.5B",
        "approx_disk_gib": 3.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "NVIDIA OpenMath 1.5B; CC-BY-4.0.",
    },
    {
        "hf_repo": "nvidia/OpenMath-Nemotron-7B",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "NVIDIA OpenMath 7B; CC-BY-4.0.",
    },
    {
        "hf_repo": "TIGER-Lab/MAmmoTH2-8B",
        "approx_disk_gib": 16.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "MAmmoTH2 tool-augmented math/science reasoning.",
    },
    {
        "hf_repo": "Snowflake/snowflake-arctic-embed-l-v2.0",
        "approx_disk_gib": 2.5,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Arctic Embed L v2; not the same checkpoint as core-queue m-long.",
    },
    {
        "hf_repo": "HuggingFaceTB/fineweb-edu-classifier",
        "approx_disk_gib": 0.5,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "FineWeb educational-quality classifier (small encoder).",
    },
    {
        "hf_repo": "ibm-granite/granite-3.3-8b-instruct",
        "approx_disk_gib": 16.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "IBM Granite 8B instruct; enterprise / management-style docs.",
    },
    {
        "hf_repo": "AdaptLLM/finance-chat",
        "approx_disk_gib": 14.0,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "Finance dialogue; Llama-2 lineage — check HF licence.",
    },
    {
        "hf_repo": "ProsusAI/finbert",
        "approx_disk_gib": 0.4,
        "gated": False,
        "target_category": "specialist",
        "covers_ollama_tags": [],
        "notes": "FinBERT financial sentiment encoder.",
    },
    # --- uncensored (abliterated / merge lines <= 120 GiB; not duplicates of core HF ids) ---
    {
        "hf_repo": "huihui-ai/DeepSeek-R1-Distill-Qwen-32B-abliterated",
        "approx_disk_gib": 62.0,
        "gated": False,
        "target_category": "uncensored",
        "covers_ollama_tags": [],
        "notes": "Abliterated R1 Qwen-32B; distinct from official DeepSeek-R1-Distill-Qwen-32B.",
    },
    {
        "hf_repo": "huihui-ai/Mistral-Small-24B-Instruct-2501-abliterated",
        "approx_disk_gib": 48.0,
        "gated": False,
        "target_category": "uncensored",
        "covers_ollama_tags": [],
        "notes": "Abliterated Mistral Small 24B; pairs with censored mistralai/Mistral-Small-24B-Instruct-2501.",
    },
    {
        "hf_repo": "huihui-ai/Qwen2.5-14B-Instruct-abliterated-v2",
        "approx_disk_gib": 28.0,
        "gated": False,
        "target_category": "uncensored",
        "covers_ollama_tags": [],
        "notes": "huihui-ai Qwen2.5 14B abliterated; registry uncensored line.",
    },
    {
        "hf_repo": "FINGU-AI/RomboUltima-32B",
        "approx_disk_gib": 62.0,
        "gated": False,
        "target_category": "uncensored",
        "covers_ollama_tags": [],
        "notes": "32B merge uncensored experimental; registry FINGU-AI/RomboUltima-32B.",
    },
]


def main() -> None:
    for e in ENTRIES:
        if e["approx_disk_gib"] > MAX_APPROX_DISK_GIB:
            raise SystemExit(f"Entry exceeds cap {MAX_APPROX_DISK_GIB}: {e['hf_repo']}")
    root = pathlib.Path(__file__).resolve().parents[1]
    out = root / "config" / "vllm-archive-manifest.yaml"
    total = round(sum(e["approx_disk_gib"] for e in ENTRIES), 1)
    doc = {
        "schema_version": 2,
        "description": "Hugging Face repos for vLLM-oriented archival (BF16/safetensors). Core queue deduped from ollama-hosting/registry/TARGET_QUEUE_ORDERED.txt; extended with specialist + uncensored hostable models.",
        "updated_note": "Regenerate via scripts/_generate_vllm_manifest.py",
        "policy": {
            "max_approx_disk_gib_per_model": MAX_APPROX_DISK_GIB,
            "excluded_over_limit": EXCLUDED_OVER_LIMIT,
        },
        "default_archive_root": "/mnt/models/d1/vllm",
        "bandwidth_mib_per_s_default": 2,
        "approx_total_disk_gib_sum": total,
        "approx_total_disk_gib_disclaimer": "Rough order-of-magnitude; HF revisions change. Entries capped at 120 GiB each; see policy.excluded_over_limit for dropped large checkpoints.",
        "entries": ENTRIES,
    }
    out.write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True), encoding="utf-8")
    n_core = sum(1 for e in ENTRIES if e.get("target_category") == "core_queue")
    n_spec = sum(1 for e in ENTRIES if e.get("target_category") == "specialist")
    n_unc = sum(1 for e in ENTRIES if e.get("target_category") == "uncensored")
    print(
        f"Wrote {out} ({len(ENTRIES)} repos, ~{total} GiB summed; "
        f"core_queue={n_core} specialist={n_spec} uncensored={n_unc})"
    )


if __name__ == "__main__":
    main()
